package com.paypal.pyplcheckout.events.model;

public enum ContingencyProcessingStatus {
    THREE_DS_JWT_1_STARTED,
    THREE_DS_JWT_2_STARTED,
    THREE_DS_LOOK_UP_STARTED,
    THREE_DS_AUTHENTICATE_STARTED,
    THREE_DS_RESOLVE_STARTED,
    THREE_DS_JWT_1_PROCESSING,
    THREE_DS_JWT_2_PROCESSING,
    THREE_DS_LOOK_UP_PROCESSING,
    THREE_DS_AUTHENTICATE_PROCESSING,
    THREE_DS_RESOLVE_PROCESSING,
    THREE_DS_JWT_1_SUCCESS,
    THREE_DS_JWT_2_SUCCESS,
    THREE_DS_LOOK_UP_SUCCESS,
    THREE_DS_AUTHENTICATE_SUCCESS,
    THREE_DS_RESOLVE_SUCCESS,
    THREE_DS_JWT_1_FAILED,
    THREE_DS_JWT_2_FAILED,
    THREE_DS_LOOK_UP_FAILED,
    THREE_DS_AUTHENTICATE_FAILED,
    THREE_DS_RESOLVE_FAILED,
    THREE_DS_SUBMIT_CLICKED,
    THREE_DS_CANCEL_CLICKED,
    THREE_DS_CARDINAL_V2_SUCCESS,
    THREE_DS_UNKNOWN_FAILURE
}
