package com.paypal.pyplcheckout.home.view.interfaces;

public interface HomeViewListener extends PayPalCompoundHeaderViewListener, PayPalShippingViewListener, PayPalCurrencyConversionViewListener, PayPalExpandedCartDetailsViewListener, PayPalSnappingRecyclerViewListener, PayPalPoliciesAndRightsLinkViewListener, PayPalCheckoutButtonClickedListener {
}
