package com.paypal.pyplcheckout.conversionrateprotection.view.interfaces;

public interface RateProtectionViewListener extends PayPalRateProtectionInfoViewListener, PayPalRateProtectionHeaderViewListener {
}
