package com.paypal.pyplcheckout.shippingmethods.view.interfaces;

public interface ShippingMethodsViewListener extends PayPalShippingMethodsHeaderViewListener, PayPalShippingMethodsRecyclerViewListener {
}
